name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Bash script
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Archive results
      uses: actions/upload-artifact@v2
      with:
        name: Python Files Archive
        path: blend-a-med.zip